import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { GoogleGenAI } from '@google/genai';
import { getStorage } from 'firebase-admin/storage';
import { randomUUID } from 'crypto';
import { AI_SERVICE_ACCOUNT, REGION, ALLOWED_ORIGINS } from '../config';
import { verifyAppCheck } from '../utils/appCheck';
import type { GenerateImageRequest, GenerateImageResponse } from '../types';

// Image generation model (different from text model)
const GEMINI_IMAGE_MODEL = 'gemini-3-pro-image-preview';
// Must use 'global' location for image generation on Vertex AI
const IMAGE_LOCATION = 'global';

/**
 * Cloud Function to generate quiz question images using Gemini 3 Pro Image
 *
 * Uses the Gemini 3 Pro Image model (gemini-3-pro-image-preview) for native
 * image generation. The generated image is uploaded to Firebase Storage.
 *
 * @see https://ai.google.dev/gemini-api/docs/image-generation
 */
export const generateQuestionImage = onCall(
  {
    region: REGION, // Function region (API uses global location)
    cors: ALLOWED_ORIGINS, // Match other AI functions
    timeoutSeconds: 120, // Image generation takes longer
    memory: '1GiB',
    maxInstances: 5,
    concurrency: 5,
    serviceAccount: AI_SERVICE_ACCOUNT,
    // App Check enabled - verifies requests come from genuine app instances
    enforceAppCheck: true,
  },
  async (request): Promise<GenerateImageResponse> => {
    // Verify App Check token (monitoring mode)
    verifyAppCheck(request);

    // Verify user is authenticated
    if (!request.auth) {
      throw new HttpsError(
        'unauthenticated',
        'You must be signed in to generate images with AI'
      );
    }

    const data = request.data as GenerateImageRequest;
    const { prompt, quizId, tempId, questionIndex } = data;

    // Validate inputs
    if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
      throw new HttpsError(
        'invalid-argument',
        'A prompt is required to generate an image'
      );
    }

    if (prompt.length > 2000) {
      throw new HttpsError(
        'invalid-argument',
        'Prompt must be less than 2000 characters'
      );
    }

    if (questionIndex === undefined || typeof questionIndex !== 'number') {
      throw new HttpsError(
        'invalid-argument',
        'Question index is required'
      );
    }

    if (!quizId && !tempId) {
      throw new HttpsError(
        'invalid-argument',
        'Either quizId or tempId is required'
      );
    }

    try {
      // Initialize Gemini client with GLOBAL location for image generation
      const client = new GoogleGenAI({
        vertexai: true,
        project: process.env.GCLOUD_PROJECT || process.env.GOOGLE_CLOUD_PROJECT,
        location: IMAGE_LOCATION, // Must be 'global' for image generation
      });

      // Generate image with Gemini 3 Pro Image
      const response = await client.models.generateContent({
        model: GEMINI_IMAGE_MODEL,
        contents: prompt,
        config: {
          responseModalities: ['TEXT', 'IMAGE'], // Must include both
          imageConfig: {
            aspectRatio: '16:9', // Good for quiz display
            imageSize: '1K', // 1K resolution (sufficient for web)
          },
        },
      });

      // Extract image from response
      const parts = response.candidates?.[0]?.content?.parts || [];

      // Find the part with inline image data
      let imageData: string | undefined;
      let mimeType: string = 'image/png';

      for (const part of parts) {
        // Type guard for parts with inlineData
        if (part && typeof part === 'object' && 'inlineData' in part && part.inlineData) {
          const inlineData = part.inlineData as { data?: string; mimeType?: string };
          if (inlineData.data) {
            imageData = inlineData.data;
            mimeType = inlineData.mimeType || 'image/png';
            break;
          }
        }
      }

      if (!imageData) {
        throw new HttpsError('internal', 'No image generated by AI');
      }

      // Determine storage path based on quizId or tempId
      const basePath = quizId ? `quizzes/${quizId}` : `temp/${tempId}`;
      const filePath = `${basePath}/questions/${questionIndex}/image.png`;

      // Upload to Firebase Storage
      const bucket = getStorage().bucket();
      const file = bucket.file(filePath);

      // Generate a download token (same approach as Firebase SDK's getDownloadURL)
      const downloadToken = randomUUID();

      // Add TTL metadata for temp images (24 hours from now)
      const isTemp = !quizId;
      const ttlMetadata = isTemp
        ? {
            tempImageExpires: new Date(
              Date.now() + 24 * 60 * 60 * 1000
            ).toISOString(),
          }
        : {};

      await file.save(Buffer.from(imageData, 'base64'), {
        metadata: {
          contentType: mimeType,
          metadata: {
            firebaseStorageDownloadTokens: downloadToken,
            ...ttlMetadata,
          },
        },
      });

      // Construct Firebase download URL (same format as getDownloadURL())
      // This works with uniform bucket-level access enabled
      const imageUrl = `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(filePath)}?alt=media&token=${downloadToken}`;

      console.log(
        `Image generated for user ${request.auth.uid}: ${filePath}`
      );

      return { imageUrl };
    } catch (error) {
      console.error('Error generating image:', error);

      // Re-throw HttpsErrors
      if (error instanceof HttpsError) {
        throw error;
      }

      // Handle specific errors
      if (error instanceof Error) {
        // Gemini content safety
        if (
          error.message.includes('safety') ||
          error.message.includes('blocked')
        ) {
          throw new HttpsError(
            'invalid-argument',
            'Image generation was blocked by content safety filters. Try a different prompt.'
          );
        }
        // Quota exceeded
        if (error.message.includes('quota')) {
          throw new HttpsError(
            'resource-exhausted',
            'AI quota exceeded. Please try again later.'
          );
        }
        // Storage errors
        if (
          error.message.includes('storage') ||
          error.message.includes('bucket') ||
          error.message.includes('access control')
        ) {
          throw new HttpsError(
            'internal',
            'Failed to save generated image. Please try again.'
          );
        }
      }

      throw new HttpsError(
        'internal',
        'Failed to generate image. Please try again.'
      );
    }
  }
);
