// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
export const firebaseConfig = {"apiKey":"API_KEY","authDomain":"sap-demo-ai-d-agents-grht.firebaseapp.com","projectId":"sap-demo-ai-d-agents-grht","storageBucket":"sap-demo-ai-d-agents-grht.appspot.com","messagingSenderId":"334963283282","appId":"1:334963283282:web:7a6c651e77918a33504149"};
