// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
// export const firebaseConfig = 
//     {"apiKey":"AIzaSyCo_YETFQt_dPa2NE4h1qrrjqdsmWePnZw",
//     "authDomain":"sap-demo-ai-d-agents-grht.firebaseapp.com",
//     "projectId":"sap-demo-ai-d-agents-grht",
//     "storageBucket":"sap-demo-ai-d-agents-grht.appspot.com",
//     "messagingSenderId":"334963283282",
//     "appId":"1:334963283282:web:7a6c651e77918a33504149"};
export const firebaseConfig = {
    apiKey: "AIzaSyCo_YETFQt_dPa2NE4h1qrrjqdsmWePnZw",
    authDomain: "sap-demo-ai-d-agents-grht.firebaseapp.com",
    projectId: "sap-demo-ai-d-agents-grht",
    storageBucket: "sap-demo-ai-d-agents-grht.firebasestorage.app",
    messagingSenderId: "880039882047",
    appId: "1:880039882047:web:963eabfeb70ef82996778a",
    measurementId: "G-8N2K0MS10P"
  };
