import { GoogleGenAI } from '@google/genai';
import { HttpsError } from 'firebase-functions/v2/https';
import { getStorage } from 'firebase-admin/storage';
import { randomUUID } from 'crypto';
import { GEMINI_IMAGE, ThinkingLevel } from './gemini';

/**
 * Generate an image with Gemini and upload to Firebase Storage.
 * Returns the public download URL.
 * NOTE: gemini-3.1-flash-image only supports 'minimal' or 'high' thinking; we
 * default to 'high' for better spatial/label accuracy on complex prompts.
 */
export async function generateAndUploadImage(
  client: GoogleGenAI,
  imagePrompt: string,
  storagePath: string,
  thinkingLevel: ThinkingLevel = ThinkingLevel.HIGH
): Promise<string> {
  const response = await client.models.generateContent({
    model: GEMINI_IMAGE,
    contents: imagePrompt,
    config: {
      responseModalities: ['TEXT', 'IMAGE'],
      imageConfig: { aspectRatio: '16:9' },
      thinkingConfig: { thinkingLevel },
    },
  });

  const parts = response.candidates?.[0]?.content?.parts || [];
  let imageData: string | undefined;
  let mimeType = 'image/png';

  for (const part of parts) {
    if (part && typeof part === 'object' && 'inlineData' in part && part.inlineData) {
      const inlineData = part.inlineData as { data?: string; mimeType?: string };
      if (inlineData.data) {
        imageData = inlineData.data;
        mimeType = inlineData.mimeType || 'image/png';
        break;
      }
    }
  }

  if (!imageData) {
    throw new HttpsError('internal', 'No image generated by AI');
  }

  const bucket = getStorage().bucket();
  const file = bucket.file(storagePath);
  const downloadToken = randomUUID();

  await file.save(Buffer.from(imageData, 'base64'), {
    metadata: {
      contentType: mimeType,
      metadata: { firebaseStorageDownloadTokens: downloadToken },
    },
  });

  return `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(storagePath)}?alt=media&token=${downloadToken}`;
}
